### ISSUE TITLE
Vaga [Dev. Front-End Júnior]

### ISSUE THREAD

**Issue by dionipires** [original-io/join-us#16]
DIONI DE JESUS PIRES

Projeto online:
http://bbrandsagencia.com.br/original.io

**Comment by guilhermemarconi** [comment]
@dionipires agora só preciso de algum PR ou algum acesso ao repositório para avaliar o código fonte do seu teste.
Consegue agilizar isso para mim?

**Comment by dionipires** [comment]
Boa tarde Guilherme,

Segue em anexo.

Att

Dioni Pires
24.999068764 | 24.99888673565
________________________________
De: Guilherme Marconi <notifications@github.com>
Enviado: quinta-feira, 12 de julho de 2018 17:39
Para: original-io/join-us
Cc: Dioni Pires; Mention
Assunto: Re: [original-io/join-us] Vaga [Dev. Front-End Júnior] (#16)


@dionipires<https://github.com/dionipires> agora só preciso de algum PR ou algum acesso ao repositório para avaliar o código fonte do seu teste.
Consegue agilizar isso para mim?

**Comment by guilhermemarconi** [comment]
@dionipires estou no Github, e não veio acesso. Você tem o e-mail do Duda, que conversou contigo?

Se tiver, pode mandar diretamente para ele, por gentileza.

**Comment by dionipires** [comment]
Desculpe, não tenho, tive uma entrevista com ele na segunda, porém não tenho o email.



Dioni Pires

24.999068764 | 24.99888673565
________________________________
De: Guilherme Marconi <notifications@github.com>
Enviado: quinta-feira, 12 de julho de 2018 17:55
Para: original-io/join-us
Cc: Dioni Pires; Mention
Assunto: Re: [original-io/join-us] Vaga [Dev. Front-End Júnior] (#16)


@dionipires<https://github.com/dionipires> estou no Github, e não veio acesso. Você tem o e-mail do Duda, que conversou contigo?

Se tiver, pode mandar diretamente para ele, por gentileza.

**Comment by dionipires** [comment]
Prezado Guilherme,

**Segue o Link do repositório:**

https://github.com/dionipires/frontend-jr-original.io

**Comment by dionipires** [comment]
Prezado @guilhermemarconi , gostaria de saber se conseguiu avaliar o código fonte do teste, se ficou alguma dúvida.

À disposição.

**Comment by guilhermemarconi** [comment]
Olá, @dionipires. Desculpe pela demora na resposta.
Avaliei o seu código e acredito que você está apto, sim, a ser entrevistado por uma vaga de Jr em nosso time.

Quando você estaria disponível para uma entrevista conosco, em nosso escritório no Centro do Rio?

**Comment by guilhermemarconi** [comment]
Sim, ele me falou. Mas como eu não estava presente, acabou que não
conseguimos fazer a avaliação como um todo.

Você teria disponibilidade para amanhã, às 11h?

Em Qua, 8 de ago de 2018 18:20, Dioni Pires <notifications@github.com>
escreveu:

**Comment by dionipires** [comment]
Bom dia Guilherme,

Teria sim, marcado.


Dioni Pires


De: Guilherme Marconi
Enviado: quinta-feira, 9 de agosto 10:13
Assunto: Re: [original-io/join-us] Vaga [Dev. Front-End Júnior] (#16)
Para: original-io/join-us
Cc: Dioni Pires, Mention


Sim, ele me falou. Mas como eu não estava presente, acabou que não
conseguimos fazer a avaliação como um todo.

Você teria disponibilidade para amanhã, às 11h?

Em Qua, 8 de ago de 2018 18:20, Dioni Pires <notifications@github.com>
escreveu:
