### ISSUE TITLE
Vaga [Júnior]

### ISSUE THREAD

**Issue by filipevx** [original-io/join-us#17]
URL do teste: https://github.com/filipevx/join-us-original
Filipe Verçosa Xavier

**Comment by guilhermemarconi** [comment]
@filipevx não consegui iniciar o ambiente. Teria como criar um README para isso?

**Comment by filipevx** [comment]
@guilhermemarconi  Boa tarde, atualizei o README.

https://github.com/filipevx/join-us-original
