### ISSUE TITLE
Vaga Front End Pleno

### ISSUE THREAD

**Issue by RudolfoSousa** [original-io/join-us#28]
Teste hospedado em: 
https://original-rudolfo.netlify.com/

Nome: Rudolfo de Sousa de Oliveira

**Comment by guilhermemarconi** [comment]
@RudolfoSousa está dando alguns erros no console e a página não está montando completamente... pode conferir, por gentileza, para que possamos avaliar?

**Comment by RudolfoSousa** [comment]
@guilhermemarconi, corrigi os erros no console. Mas acredito que a página não esteja carregano corretamente por conta do dB.

Eu criei um json e usei o json-server para criar um servidor e alimentar o React. Ele está configurado para rodar na porta 4000 "json-server -p 4000 db.son" -> dentro da pasta 'db'

Em uma outra janela do terminal eu uso o npm start para rodar o React.
