### ISSUE TITLE
Vaga Pleno

### ISSUE THREAD

**Issue by LeoLFerraz** [original-io/join-us#40]
Olá! Aqui estão as informações requisitadas para a entrega:

**Projeto hospedado: ** http://ec2-18-229-118-221.sa-east-1.compute.amazonaws.com/
** Nome Completo: ** Leonardo de Lanna Ferraz
** Pull Request: ** https://github.com/original-io/join-us/pull/39

Coloquei observações e detalhes da implementação no readme do rep.

Abraços!

**Comment by 0000marcell** [comment]
Bom dia Leo, Obrigado pela participação, a equipe de design e desenvolvimento vai fazer uma analize do seu teste até o final da semana que vem e vamos passar o feedback tanto pra você quanto pro RH, que continuará o processo, por favor nos envie o seu e-mail atual

Abraços
