### ISSUE TITLE
Vaga [Júnior]

### ISSUE THREAD

**Issue by Henriquepb22** [original-io/join-us#41]
Url do meu teste hospedado: https://inspiring-wescoff-23de1d.netlify.com/
Nome completo: **Henrique Pereira Barros**
Repositório: https://github.com/Henriquepb22/join-us

**Comment by 0000marcell** [comment]
Bom dia Henrique, Obrigado pela participação, a equipe de design e desenvolvimento vai fazer uma analize do seu teste até o final da semana que vem e vamos passar o feedback tanto pra você quanto pro RH, que continuará o processo, por favor nos envie o seu e-mail atual

Abraços

**Comment by Henriquepb22** [comment]
Boa noite, @0000marcell 
Segue meu email: henriquepbdev@gmail.com
Obrigado!

**Comment by fabriciodanioj** [comment]
Meu email: fabriciodanioj@gmail.com

Em Qua, 4 de mar de 2020 20:33, Henrique <notifications@github.com>
escreveu:
