### ISSUE TITLE
Vaga [Júnior]

### ISSUE THREAD

**Issue by fabriciodanioj** [original-io/join-us#43]
Nome: Fabrício Dani de Oliveira Júnior
URL: https://laughing-wilson-18f531.netlify.com/
Repo: https://github.com/fabriciodanioj/join-us

**Comment by fabriciodanioj** [comment]
Commit History

**Comment by 0000marcell** [comment]
Bom dia Fabricio, Obrigado pela participação, a equipe de design e desenvolvimento vai fazer uma analize do seu teste até o final da semana que vem e vamos passar o feedback tanto pra você quanto pro RH, que continuará o processo, por favor nos envie o seu e-mail atual

Abraços
