### ISSUE TITLE
Vaga [Júnior]

### ISSUE THREAD

**Issue by Tsuna2221** [original-io/join-us#45]
Nome: Thiago Barroso da Silva
URL: https://originalio.netlify.com
Pull: https://github.com/original-io/join-us/pull/44

**Comment by 0000marcell** [comment]
Bom dia Thiago, Obrigado pela participação, a equipe de design e desenvolvimento vai fazer uma analize do seu teste até o final da semana que vem e vamos passar o feedback tanto pra você quanto pro RH, que continuará o processo, por favor nos envie o seu e-mail atual

Abraços

**Comment by Tsuna2221** [comment]
Ok, obrigado.
O e-mail é: tsuna2221@live.com
