### ISSUE TITLE
Vaga Front-End Jr

### ISSUE THREAD

**Issue by lgdevlop** [original-io/join-us#6]
[URL do teste hospedado: ](https://lgdevlop.com/teste-original.io/)
Nome: Leonardo Gomes de Lima
link para o repositório: https://github.com/lgdevlop/teste-original.io

**Comment by DudaBastosOTX** [comment]
Leonardo boa tarde, teria horário disponível essa semana para uma entrevista? me envie seu currículo para duda.bastos@original.io

**Comment by lgdevlop** [comment]
Duda boa tarde!
As informações solicitadas foram encaminhadas para seu e-mail!
Forte abraço.
