### ISSUE TITLE
Vaga Júnior

### ISSUE THREAD

**Issue by renanlimabl** [original-io/join-us#8]
Link do do site, resultado final:
https://lucid-dubinsky-f06a06.netlify.com/#

- 100% Responsivo,
- Compatível com os browsers, 
- Uso de Sass (scss) e BEM.

Link do Pull Request:
https://github.com/original-io/join-us/pull/9

Nome: Renan Lima Barreto Leite

**Comment by DudaBastosOTX** [comment]
Renan boa tarde, teria horário disponível essa semana para uma entrevista? me envie seu currículo para duda.bastos@original.io

**Comment by renanlimabl** [comment]
@DudaBastosOTX Boa tarde, tenho sim, enviei a resposta por e-mail.
